# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: 0.0.87.$(rev:r)
trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

resources:
  repositories:
  - repository: pipelines  # identifier (A-Z, a-z, 0-9, and underscore)
    type: github  # see the following "Type" topic
    name: hangar18rip/azdo-pipeline-library
    endpoint: 'hangar18rip'
    # ref: 'refs/heads/bug/browerinstall'

extends:
  template: h18.SeleniumWithSpecFlow.yml@pipelines
  parameters:
    SonarCloudConnection: 'SonarCloud'
    SonarCloudOrganization: 'odelmotte'
    SonarCloudProjectKey: 'hangar18rip.h18.SeleniumWithSpecFlow.Edge'
    SonarCloudProjectName: '[h18] h18.SeleniumWithSpecFlow.Edge'
    NuGetConnection: 'NuGet'
    BrowserName: 'microsoft-edge'
    BrowserVersion: 87
